-- =====================================================================
-- 071_svi_metric_overrides.sql
-- SVI Wave 5b-2a — per-church metric overrides (the multi-tenant window unlock).
--
-- A church may override a metric's window (compute_config.lookback_days) or any
-- other compute_config knob. The override JSONB shallow-merges over the GLOBAL
-- svi_metrics.compute_config in the compute-svi-weekly EF. svi_metrics stays
-- GLOBAL (#032) — this table carries the per-church deltas only.
--
-- Mirrors the proven svi_weight_profiles per-church RLS pattern (migration 032):
-- 4 tenant policies on auth_church_id() + autostamp trigger. The service-role EF
-- bypasses RLS. FLAT (#209), self-verify rerun-until-true (#210).
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.svi_metric_overrides (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  church_id               uuid NOT NULL,
  metric_key              text NOT NULL,
  compute_config_override jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active               boolean NOT NULL DEFAULT true,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT svi_metric_overrides_church_metric_key UNIQUE (church_id, metric_key)
);

-- 4 tenant policies on auth_church_id() (mirror svi_weight_profiles #032)
DROP POLICY IF EXISTS svi_metric_overrides_tenant_select ON public.svi_metric_overrides;
DROP POLICY IF EXISTS svi_metric_overrides_tenant_insert ON public.svi_metric_overrides;
DROP POLICY IF EXISTS svi_metric_overrides_tenant_update ON public.svi_metric_overrides;
DROP POLICY IF EXISTS svi_metric_overrides_tenant_delete ON public.svi_metric_overrides;
CREATE POLICY svi_metric_overrides_tenant_select ON public.svi_metric_overrides FOR SELECT TO authenticated USING (church_id = public.auth_church_id());
CREATE POLICY svi_metric_overrides_tenant_insert ON public.svi_metric_overrides FOR INSERT TO authenticated WITH CHECK (church_id = public.auth_church_id());
CREATE POLICY svi_metric_overrides_tenant_update ON public.svi_metric_overrides FOR UPDATE TO authenticated USING (church_id = public.auth_church_id()) WITH CHECK (church_id = public.auth_church_id());
CREATE POLICY svi_metric_overrides_tenant_delete ON public.svi_metric_overrides FOR DELETE TO authenticated USING (church_id = public.auth_church_id());

-- autostamp church_id from JWT on insert (client sends NO church_id)
DROP TRIGGER IF EXISTS trg_set_church_id ON public.svi_metric_overrides;
CREATE TRIGGER trg_set_church_id BEFORE INSERT ON public.svi_metric_overrides
  FOR EACH ROW EXECUTE FUNCTION public.set_church_id_from_jwt();

ALTER TABLE public.svi_metric_overrides ENABLE ROW LEVEL SECURITY;

INSERT INTO public.schema_migrations (version, filename, note)
VALUES ('071','071_svi_metric_overrides.sql','Wave 5b-2a: per-church svi_metric_overrides (compute_config_override JSONB, UNIQUE(church_id,metric_key), 4 tenant RLS + autostamp); svi_metrics stays global')
ON CONFLICT (version) DO NOTHING;

-- self-verify (rerun-until-true): expect all_ok = PASS
SELECT
  (SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_name='svi_metric_overrides')                      AS tbl,
  (SELECT count(*) FROM pg_policies WHERE schemaname='public' AND tablename='svi_metric_overrides')                                       AS policies,
  (SELECT relrowsecurity FROM pg_class WHERE oid='public.svi_metric_overrides'::regclass)                                                 AS rls_on,
  (SELECT count(*) FROM pg_trigger WHERE tgrelid='public.svi_metric_overrides'::regclass AND tgname='trg_set_church_id')                  AS autostamp,
  CASE WHEN (SELECT count(*) FROM pg_policies WHERE schemaname='public' AND tablename='svi_metric_overrides')=4
        AND (SELECT relrowsecurity FROM pg_class WHERE oid='public.svi_metric_overrides'::regclass)=true
        AND (SELECT count(*) FROM pg_trigger WHERE tgrelid='public.svi_metric_overrides'::regclass AND tgname='trg_set_church_id')=1
       THEN 'PASS' ELSE 'FAIL' END                                                                                                        AS all_ok;
